import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import Navbar1 from "@/shared/components/Navbar";
import { DirectionProvider } from "@base-ui/react";
import localFont from "next/font/local";
import Footer from "@/features/home/components/Footer";

const ibm_sans = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});
const atyp = localFont({
  src: [
    {
      path: "../assets/fonts/atyp/AtypText-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/atyp/AtypText-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/atyp/AtypText-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/atyp/AtypText-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={`${locale === "ar" ? ibm_sans.className : atyp.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <DirectionProvider direction={locale === "ar" ? "rtl" : "ltr"}>
          <NextIntlClientProvider>
            <Navbar1 />
            {children}
            <Footer />
          </NextIntlClientProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
